// Timeline bookmarks: user-marked moments of interest on the shared review
// timeline, persisted with the project so a repeat review session can jump
// straight back to them. Ids are generated by the caller (crypto.randomUUID,
// same as clip ids) so these stay pure and deterministic to test.
import type { Bookmark } from "../types/project";

export function sortBookmarks(bookmarks: Bookmark[]): Bookmark[] {
  return [...bookmarks].sort((a, b) => a.timeSeconds - b.timeSeconds);
}

export function addBookmark(bookmarks: Bookmark[], bookmark: Bookmark): Bookmark[] {
  return sortBookmarks([...bookmarks, bookmark]);
}

export function removeBookmark(bookmarks: Bookmark[], id: string): Bookmark[] {
  return bookmarks.filter((b) => b.id !== id);
}

export function renameBookmark(bookmarks: Bookmark[], id: string, label: string): Bookmark[] {
  return bookmarks.map((b) => (b.id === id ? { ...b, label } : b));
}
