// Timeline bookmarks: user-marked moments of interest on the shared review
// timeline, persisted with the project so a repeat review session can jump
// straight back to them. Ids are generated by the caller (crypto.randomUUID,
// same as clip ids) so these stay pure and deterministic to test.
import type { Bookmark } from "../types/project";
import { circularOffsetSeconds } from "./timeOfDay";

/**
 * Where a bookmark currently sits on the shared timeline, re-derived from
 * its real-world time-of-day against the CURRENT anchor every call rather
 * than cached — so it keeps pointing at the same moment even after the
 * anchor clip (and thus the timeline's own coordinate system) shifts, e.g.
 * when a clip starting earlier than the current earliest one is added.
 * Falls back to the position it was created at only when there was no
 * anchor to derive a real time-of-day from in the first place (a single
 * untimed clip), or for bookmarks saved before timeOfDaySeconds existed.
 */
export function bookmarkTimelineSeconds(bookmark: Bookmark, anchorSeconds: number | null): number {
  if (bookmark.timeOfDaySeconds === null || anchorSeconds === null) {
    return bookmark.fallbackTimeSeconds;
  }
  return circularOffsetSeconds(anchorSeconds, bookmark.timeOfDaySeconds);
}

export function sortBookmarks(bookmarks: Bookmark[], anchorSeconds: number | null): Bookmark[] {
  return [...bookmarks].sort(
    (a, b) => bookmarkTimelineSeconds(a, anchorSeconds) - bookmarkTimelineSeconds(b, anchorSeconds),
  );
}

export function addBookmark(bookmarks: Bookmark[], bookmark: Bookmark): Bookmark[] {
  return [...bookmarks, bookmark];
}

export function removeBookmark(bookmarks: Bookmark[], id: string): Bookmark[] {
  return bookmarks.filter((b) => b.id !== id);
}

export function renameBookmark(bookmarks: Bookmark[], id: string, label: string): Bookmark[] {
  return bookmarks.map((b) => (b.id === id ? { ...b, label } : b));
}
